### ISSUE TITLE
TTS_Starter_Notebook Unable to Load .onnx Model File Due to Directory Paths Not Found in config.json

### ISSUE THREAD

**Issue by obedgyamfi** [brilla-ai/brilla-ai#119]
**Describe the bug**

The TTS\_Starter\_Notebook is unable to load the .onnx model file which is external to the directory specified in the json file("speakers_file:") due to an issue with accessing certain file paths specified in the model's .config.json file.

**Error**: 
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Isaac sesi/VITS model/sesi_vits/traineroutput/tts_multispeaker-October-13-2023_11+03AM-0000000/speakers.pth'

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/speakers.pth'

**To Reproduce**

1. Open the TTS\_Starter\_Notebook in a Jupyter notebook or Colab environment external to any original development directory.
2. Run the code cells to install the necessary dependencies and libraries.
3. Attempt to load the .onnx model file by running the "Loading the student model" and "Loading the quizmistress model" code cell
4. Observe the error message indicating that the specified file paths in the "student config.json" and "quizmistress config.json" file cannot be accessed.

**Expected behavior**

The .onnx model file should be able to be loaded successfully, allowing the user to perform inference and synthesize speech using the TTS model.

**Screenshots of Errors**

![Screenshot from 2024-05-28 06-06-42](https://github.com/brilla-ai/brilla-ai/assets/66894594/aa6f283a-39cc-4d25-9793-20af048987ae)
![Screenshot from 2024-05-28 06-07-40](https://github.com/brilla-ai/brilla-ai/assets/66894594/67519a13-bfb8-4d4c-9b41-3f8957061f99)

**Desktop (please complete the following information):**

- OS: Linux 
- Browser: Mozilla Firefox 126.0

**Additional context**

The issue may be related to the fact that the .config.json file specifies file paths that do not exist in the users directory.

Possible solutions to the problem could include:
- Including the folders or files to the brilla-ai github repository
- Enable the user to modify the config.json file to include the path to the folders or files.

**Comment by Nanayeb34** [comment]
@obedgyamfi 
that was a bug. The `AI Voice Models` hackathon folder has been updated to include the respective speaker files. Set the `speakers_file` key in the respective config.json to the path where the speaker file would be stored on your local device or Google Drive .

**Comment by obedgyamfi** [comment]
Thank you.
