### ISSUE TITLE
README for TTS page

### ISSUE THREAD

**Issue by Nanayeb34** [brilla-ai/brilla-ai#81]
**Describe the issue**

Current TTS readme is vague and doesn't describe in detail the function of the TTS page and how to run the script.

**Expected behaviour**
A detailed ReadMe on the TTS page and how to run the script.

**Comment by wsedor** [comment]
@Nanayeb34 great issue. can you please add in any relevant labels as well for it and if you want to assign to yourself or leave blank as well for others to pick up along the way
